name: Transcripción de video con Whisper

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      video_url:
        description: "URL del video"
        required: true

jobs:
  transcribe-video:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Descargar el código fuente
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      # Paso 3: Cachear dependencias de Python
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Paso 4: Instalar dependencias necesarias
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 5: Descargar el video usando yt-dlp
      - name: Download video
        run: yt-dlp -o "video_temp.mp4" "${{ github.event.inputs.video_url }}"

      # Paso 6: Ejecutar el script para transcribir (ya existente en el repositorio)
      - name: Transcribe video
        run: python transcribe.py

      # Paso 7: Subir el archivo transcrito como artefacto
      - name: Upload transcription
        uses: actions/upload-artifact@v3
        with:
          name: transcription
          path: transcription.txt

      # Paso 8: Limpiar archivos temporales
      - name: Cleanup
        run: |
          rm -f video_temp.mp4 transcription.txt || true



