name: Transcripción de video con Whisper

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: "URL del video"
        required: true

jobs:
  transcribe-video:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Descargar el código fuente
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Paso 3: Cachear dependencias de Python
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Paso 4: Instalar dependencias necesarias
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 5: Descargar el video usando yt-dlp
      - name: Download video
        run: yt-dlp -o "video_temp.mp4" "${{ github.event.inputs.video_url }}"

      # Paso 6: Extraer audio del video (solo audio, sin video)
      - name: Extract audio from video
        run: |
          ffmpeg -i video_temp.mp4 -vn -acodec pcm_s16le -ar 44100 -ac 2 audio_temp.wav

      # Paso 7: Ejecutar el script para transcribir el audio
      - name: Transcribe audio
        run: python transcribe.py --audio audio_temp.wav

      # Paso 8: Generar resumen utilizando la API de Groq
      - name: Generate Summary
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python summarize.py  # Llama al script que genera el resumen

      # Paso 9: Subir los archivos como artefactos
      - name: Upload transcription and summary
        uses: actions/upload-artifact@v3
        with:
          name: transcription-and-summary
          path: |
            transcription.txt
            summary.md

      # Paso 10: Limpiar archivos temporales
      - name: Cleanup
        run: |
          rm -f video_temp.mp4 audio_temp.wav transcription.txt summary.md || true

