name: Transcripción y Resumen Sharepoint
on:
  workflow_dispatch:
    inputs:
      video_url:
        description: "URL del video de SharePoint"
        required: true
      language:
        description: "Idioma del video (es/en)"
        required: true
        default: 'es'

jobs:
  transcribe-video:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          python -m pip install --upgrade pip
          pip install yt-dlp requests beautifulsoup4

      - name: Save cookies
        run: |
          echo "${{ secrets.SHAREPOINT_COOKIES }}" > cookies.txt

      - name: Download video
        id: download
        run: |
          yt-dlp --cookies cookies.txt \
                 --extract-audio \
                 --audio-format wav \
                 --audio-quality 0 \
                 -o "audio_temp.%(ext)s" \
                 "${{ github.event.inputs.video_url }}"

      - name: Transcribe audio
        if: success()
        env:
          WHISPER_MODEL: "base"
          LANGUAGE: ${{ github.event.inputs.language }}
        run: python transcribe.py --audio audio_temp.wav --model ${WHISPER_MODEL} --language ${LANGUAGE}

      - name: Generate Summary
        if: success()
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python summarize.py

      - name: Upload results
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: transcription-and-summary-${{ github.run_id }}
          path: |
            transcription.txt
            summary.md
          retention-days: 7

      - name: Cleanup
        if: always()
        run: rm -f audio_temp.* cookies.txt transcription.txt summary.md || true
