name: Transcripción y Resumen Sharepoint

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: "URL del video (incluido SharePoint)"
        required: true

jobs:
  transcribe-video:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Descargar el código fuente
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      # Paso 3: Cachear dependencias de Python
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Paso 4: Instalar dependencias necesarias
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 5: Descargar cookies (si están como secreto)
      - name: Save cookies
        run: echo "${{ secrets.SHAREPOINT_COOKIES }}" > cookies.txt

      # Paso 6: Descargar el video usando yt-dlp y cookies
      - name: Download video
        run: yt-dlp --cookies cookies.txt -o "video_temp.mp4" '${{ github.event.inputs.video_url }}'

      # Paso 7: Extraer audio del video
      - name: Extract audio from video
        run: ffmpeg -i video_temp.mp4 -vn -acodec pcm_s16le -ar 44100 -ac 2 audio_temp.wav

      # Paso 8: Ejecutar el script para transcribir el audio
      - name: Transcribe audio
        run: python transcribe.py --audio audio_temp.wav

      # Paso 9: Generar resumen utilizando la API de Groq
      - name: Generate Summary
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python summarize.py

      # Paso 10: Subir los archivos como artefactos
      - name: Upload transcription and summary
        uses: actions/upload-artifact@v3
        with:
          name: transcription-and-summary
          path: |
            transcription.txt
            summary.md

      # Paso 11: Limpiar archivos temporales
      - name: Cleanup
        run: |
          rm -f video_temp.mp4 audio_temp.wav cookies.txt transcription.txt summary.md || true
